### ISSUE TITLE
Says memes but no memes

### ISSUE THREAD

**Issue by jflewis** [kpollich/memes#1]
Can we add some more memes here, or a README to clarify where the memes are?

**Comment by kpollich** [comment]
I can look into this in build candidate 1 (we should have an alpha by end of quarter), but no guarantees. We have a few technical writers contributing, and I can bring up documentation, etc with them.

**Comment by jflewis** [comment]
Okay that's great to hear. Thanks for getting back to me so soon.

**Comment by kpollich** [comment]
thank you john
